setwd("~/Documents/R/Exploratoty data analysis")
epc = read.delim("household_power_consumption.txt",sep=";")
summary(epc)
epc$Date=as.Date(epc$Date, "%d/%m/%Y")
epc$Global_active_power= as.numeric(epc$Global_active_power)
epc$Voltage= as.numeric(epc$Voltage)
epc$Global_reactive_power= as.numeric(epc$Global_reactive_power)
epc$Sub_metering_1= as.numeric(epc$Sub_metering_1)
epc$Sub_metering_2= as.numeric(epc$Sub_metering_2)
epc$Sub_metering_3= as.numeric(epc$Sub_metering_3)
epc2day=subset(epc, Date >= '2007-02-01' & Date <= '2007-02-02')
epc2day$FinalTime = as.POSIXct(paste(epc2day$Date, as.character(epc2day$Time)))
summary(epc2day)
plot(epc2day$FinalTime,epc2day$Sub_metering_1, type="l", xlab="", ylab = "Energy Sub Metering", col="black",cex.lab=0.8, cex.axis=0.7,cex.main=0.8)
lines(epc2day$FinalTime,epc2day$Sub_metering_2, col="red")
lines(epc2day$FinalTime,epc2day$Sub_metering_3, col="blue")
legend("topright", legend =c("sub_metering_1  ","sub_metering_2  ","sub_metering_3  "), lty=c(1,1,1), col=c("black","red","blue"), cex=0.7)
dev.copy(png, file = "plot3.png")
dev.off()
